SYSROOT_USER="/home/$USER/sysroot"
SYSROOT_BIN_PATH="$SYSROOT_USER/bin"
SYSROOT_BIN_PATH="$SYSROOT_USER/sbin:$SYSROOT_BIN_PATH"
SYSROOT_BIN_PATH="$SYSROOT_USER/usr/local/sbin:$SYSROOT_BIN_PATH"
SYSROOT_BIN_PATH="$SYSROOT_USER/bin:$SYSROOT_BIN_PATH"
SYSROOT_BIN_PATH="$SYSROOT_USER/usr/bin:$SYSROOT_BIN_PATH"
SYSROOT_BIN_PATH="$SYSROOT_USER/usr/local/bin:$SYSROOT_BIN_PATH"
export PATH=$SYSROOT_BIN_PATH:$PATH

SYSROOT_LIB_PATH="$SYSROOT_USER/lib"
SYSROOT_LIB_PATH="$SYSROOT_USER/usr/lib:$SYSROOT_LIB_PATH"
SYSROOT_LIB_PATH="$SYSROOT_USER/lib64:$SYSROOT_LIB_PATH"
SYSROOT_LIB_PATH="$SYSROOT_USER/usr/lib64:$SYSROOT_LIB_PATH"
export LD_LIBRARY_PATH="$SYSROOT_LIB_PATH:$LD_LIBRARY_PATH"
